# Download csv file from a given URL and save it to a specified directory
URL="https://docs.google.com/spreadsheets/d/e/2PACX-1vTw97FS3eOFbYlqY8j7wWrBd3yrDaG6hqPclYJdPrnvd7t9U2DNz5xXNK4F0iesyHIKEkx9weLz-69a/pub"
GID_GENERALIST="897920130"
GID_CANCER="14394643"
GID_DEVELOPMENT="1596020802"
GID_ECOLOGY_EVOLUTION="1379256167"
GID_GENETICS_GENOMICS="1379563174"
GID_HEALTH="507847855"
GID_IMMUNOLOGY="1030012941"
GID_MOLECULAR_CELLULAR_BIOLOGY="86261319"
GID_NEUROSCIENCES="312916140"
GID_PLANTS="818438400"
rm -rf ./data_extracted
mkdir -p ./data_extracted
wget -O ./data_extracted/generalist.csv "${URL}?gid=${GID_GENERALIST}&single=true&output=csv"
wget -O ./data_extracted/cancer.csv "${URL}?gid=${GID_CANCER}&single=true&output=csv"
wget -O ./data_extracted/development.csv "${URL}?gid=${GID_DEVELOPMENT}&single=true&output=csv"
wget -O ./data_extracted/ecology_evolution.csv "${URL}?gid=${GID_ECOLOGY_EVOLUTION}&single=true&output=csv"
wget -O ./data_extracted/genetics_genomics.csv "${URL}?gid=${GID_GENETICS_GENOMICS}&single=true&output=csv"
wget -O ./data_extracted/health.csv "${URL}?gid=${GID_HEALTH}&single=true&output=csv"
wget -O ./data_extracted/immunology.csv "${URL}?gid=${GID_IMMUNOLOGY}&single=true&output=csv"
wget -O ./data_extracted/molecular_cellular_biology.csv "${URL}?gid=${GID_MOLECULAR_CELLULAR_BIOLOGY}&single=true&output=csv"
wget -O ./data_extracted/neurosciences.csv "${URL}?gid=${GID_NEUROSCIENCES}&single=true&output=csv"
wget -O ./data_extracted/plants.csv "${URL}?gid=${GID_PLANTS}&single=true&output=csv"